version: '3.1'

services:
  springboot:
    image: iamchikka/spring-swarm:latest
    restart: always # This will be ignored if we deploy in docker swarm
    environment:
    - MONGO_DB_HOSTNAME=mongodb
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb123
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    networks:
    - spring-mongo-network 
    deploy:  # This will be considered only in docker swarm.
      replicas: 2
      update_config:
        parallelism: 1
        delay: 20s
      restart_policy:
        condition: on-failure
        delay: 10s
        max_attempts: 5

  mongodb:
    image: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb123
    volumes:
    - mongo-database:/data/db
    restart: always
    networks:
    - spring-mongo-network
    
volumes:
  mongo-database:
    external: true
    
networks:
  spring-mongo-network:
    external: true
