apiVersion: v1
kind: Namespace
metadata:
 name: spring-ns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployspring
  namespace: spring-ns
spec:
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      containers:
      - name: spring-container
        image: iamchikka/springboot-mongodb:latest
        resources:
          requests:
           cpu: "400m"
           memory: "256Mi"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
        - name: MONGO_DB_HOSTNAME
          value: svc-mongodbserver.default.svc.cluster.local
        - name: MONGO_DB_USERNAME
          value: admin  
        - name: MONGO_DB_PASSWORD
          value: admin
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: springhpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: deployspring
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 15
  - type: Resource
    resource:
     name: memory
     target:
      type: Utilization
      averageUtilization: 20
---
apiVersion: v1
kind: Service
metadata:
  name: svc-spring
  namespace: spring-ns
spec:
  type: NodePort
  selector: 
   app: spring-app 
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30900
---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: mongo-rc
spec:
  replicas: 1
  selector:
   matchLabels:
    app: mongodbserver
  template:
    metadata:
      name: mongodbsever-app
      labels:
        app: mongodbserver
    spec:
      containers:
      - name: mongo-container
        image: mongo
        ports:
        - containerPort:  27017
        resources:
         limits:
          cpu: "400m"
          memory: "400Mi"
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: admin
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: admin
---
apiVersion: v1
kind: Service
metadata:
  name: svc-mongodbserver
spec:
  selector:
    app: mongodbserver
  ports:
  - port: 27017
    targetPort: 27017
